language: python
dist: bionic
sudo: false
matrix:
  include:
    - python: 3.8
      env: TOXENV=check PYTEST_NO_COVERAGE=1
    - python: 3.8
      env: TOXENV=docs PYTEST_NO_COVERAGE=1
    - python: 3.8
      env: TOXENV=mypy PYTEST_NO_COVERAGE=1

install:
  - pip install -U pip
  - pip install tox tox-travis

script: tox
