language: python
dist: bionic
sudo: false
cache: pip
matrix:
  include:
    - python: 3.8
      env: TOXENV=check PYTEST_NO_COVERAGE=1
    - python: 3.8
      env: TOXENV=docs PYTEST_NO_COVERAGE=1
    - python: 3.8
      env: TOXENV=mypy PYTEST_NO_COVERAGE=1
    - python: pypy3.6-7.2.0
      env: TOXENV=pypy3

install:
  - pip install -U pip
  - pip install tox tox-travis coveralls
script: tox
after_success:
  - |
    if [[ "$PYTEST_NO_COVERAGE" != 1 ]]; then
      coveralls
    fi
