language: python
dist: bionic
sudo: false
cache: pip
matrix:
  include:
    - python: 3.8
      env: TOXENV=check
    - python: 3.8
      env: TOXENV=docs
    - python: 3.8
      env: TOXENV=mypy
    - python: pypy3.6-7.2.0
      env: TOXENV=pypy3

install:
  - pip install -U pip
  - pip install tox tox-travis coveralls

script:
  - tox

after_success:
  # Hack for coveralls to find sources
  - sed -E -ie 's/.tox.py(36|37|38|py3).(lib.python[2-3].[0-9].)?site-packages/src/g' .coverage
  - coveralls

