language: python
dist: bionic
sudo: false
cache: pip
matrix:
  include:
    - python: 3.8
      env: TOXENV=check PYTEST_NO_COVERAGE=1
    - python: 3.8
      env: TOXENV=docs PYTEST_NO_COVERAGE=1
    - python: 3.8
      env: TOXENV=mypy PYTEST_NO_COVERAGE=1
    - python: pypy3.6-7.2.0
      env: TOXENV=pypy3

install:
  - pip install -U pip
  - pip install tox tox-travis coveralls

script:
  - tox

after_success:
  after_success:
  - |
    if [[ "$PYTEST_NO_COVERAGE" != 1 ]]; then
      # Hack for coveralls to find sources
      sed -E -ie 's/.tox.py(36|37|38|py3).(lib.python[2-3].[0-9].)?site-packages/src/g' .coverage
      coverage xml --ignore-errors
      coveralls
    fi
